# This file is a template, and might need editing before it works on your project.
# https://hub.docker.com/r/google/dart
image: fischerscode/flutter:stable

variables:

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'

cache:
  paths:
    - .pub-cache/global_packages

stages:
  - test

before_script:
  - git config --global --add safe.directory /builds/mb2.cto/gp-banx-app
  - export PATH="$PATH":"$HOME/.flutter-sdk/.pub-cache/bin"
  - flutter pub get
  - flutter pub global activate junitreport
  - dart pub global activate melos

test:
  stage: test
  script:
    - flutter pub global run melos run qualitycheck

  tags:
    - shared
  artifacts:
    paths:
      - coverage/
    expire_in: 5 days
  only:
    - merge_requests
