name: banx
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2

  designsystem:
    path: core/designsystem
  data:
    path: core/data
  datepicker:
    path: core/datepicker
  domain:
    path: core/domain
  utils:
    path: core/utils
  phone:
    path: feature/phone
  referral:
    path: feature/referral
  identity:
    path: feature/identity
  face_detection:
    path: feature/face_detection
  onboarding_password:
    path: feature/onboarding_password
  kyc_status:
    path: feature/kyc_status
  create_password:
    path: feature/create_password
  confirm_password:
    path: feature/confirm_password
  enable_biometric:
    path: feature/enable_biometric
  onboarding_face:
    path: feature/onboarding_face
  select_card:
    path: feature/select_card
  verify_otp:
    path: feature/verify_otp
  splash:
    path: feature/splash
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path_android: "assets/images/x1.png"
  image_path_ios: "assets/images/x1.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 24 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
    image_path: "assets/images/x1.png"

flutter:
  fonts:
    - family: IRANSansXFaNum
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Black.ttf
        - asset: assets/fonts/IRANSansXFaNum-Bold.ttf
        - asset: assets/fonts/IRANSansXFaNum-DemiBold.ttf
        - asset: assets/fonts/IRANSansXFaNum-ExtraBlack.ttf
        - asset: assets/fonts/IRANSansXFaNum-ExtraBold.ttf
        - asset: assets/fonts/IRANSansXFaNum-Heavy.ttf
        - asset: assets/fonts/IRANSansXFaNum-Light.ttf
        - asset: assets/fonts/IRANSansXFaNum-Medium.ttf
        - asset: assets/fonts/IRANSansXFaNum-Regular.ttf
        - asset: assets/fonts/IRANSansXFaNum-Thin.ttf
        - asset: assets/fonts/IRANSansXFaNum-UltraLight.ttf


  uses-material-design: true

  assets:
    - assets/images/enable_face.png
    - assets/images/kyc_status.png
    - assets/images/metal_card_silver.png
    - assets/images/metal_card_gold.png
    - assets/images/metal_card_black.png
    - assets/images/silver.png
    - assets/images/gold.png
    - assets/images/black.png
    - assets/images/referral_frame.png
    - assets/images/x1.png
    - assets/images/banx-logo.png
    - assets/images/banx-logo.svg
    - assets/images/slide-01.png
    - assets/images/slide-02.png
    - assets/images/slide-03.png
    - assets/images/circle_user.svg
    - assets/images/image-key.png
    - assets/images/onboarding_face.png