name: banx
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  dio: ^5.4.3+1
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  persian_datetime_picker: ^2.7.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.2.0
  shamsi_date: ^1.0.2
  flutter_spinkit: ^5.2.1
  toastification: ^2.0.0
  flip_card: ^0.7.0
  pinput: ^5.0.0
  camera: ^0.11.0+1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  injectable: ^2.4.2
  google_mlkit_face_detection: ^0.11.0
  flutter_animation_progress_bar: ^2.3.1
  video_player: ^2.2.19
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner:
  injectable_generator:
  json_serializable: ^6.7.1

flutter_launcher_icons:
  image_path_android: "assets/images/x1.png"
  image_path_ios: "assets/images/x1.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 24 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
    image_path: "assets/images/x1.png"

flutter:
  fonts:
    - family: IRANSansXFaNum
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Black.ttf
        - asset: assets/fonts/IRANSansXFaNum-Bold.ttf
        - asset: assets/fonts/IRANSansXFaNum-DemiBold.ttf
        - asset: assets/fonts/IRANSansXFaNum-ExtraBlack.ttf
        - asset: assets/fonts/IRANSansXFaNum-ExtraBold.ttf
        - asset: assets/fonts/IRANSansXFaNum-Heavy.ttf
        - asset: assets/fonts/IRANSansXFaNum-Light.ttf
        - asset: assets/fonts/IRANSansXFaNum-Medium.ttf
        - asset: assets/fonts/IRANSansXFaNum-Regular.ttf
        - asset: assets/fonts/IRANSansXFaNum-Thin.ttf
        - asset: assets/fonts/IRANSansXFaNum-UltraLight.ttf


  uses-material-design: true

  assets:
    - assets/images/card-banner.png
    - assets/images/enable_face.png
    - assets/images/kyc_status.png
    - assets/images/metal_card_silver.png
    - assets/images/metal_card_gold.png
    - assets/images/metal_card_black.png
    - assets/images/silver.png
    - assets/images/gold.png
    - assets/images/black.png
    - assets/images/referral_frame.png
    - assets/images/x1.png
    - assets/images/x1_white.png
    - assets/images/banx-logo.png
    - assets/images/banx-logo.svg
    - assets/images/slide-01.png
    - assets/images/slide-02.png
    - assets/images/slide-03.png
    - assets/images/circle_user.svg
    - assets/images/image-key.png
    - assets/images/onboarding_face.png
    - assets/images/blue-logo.png
    - assets/images/chip.png
    - assets/images/saman-bank.png
    - assets/images/checked.png
