name: banx
publish_to: 'none'

version: 0.1.0+3

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.8
  dio: ^5.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  persian_datetime_picker: ^3.0.2
  persian_number_utility: ^1.1.4
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.2.0
  shamsi_date: ^1.0.2
  toastification: ^2.3.0
  flip_card: ^0.7.0
  pinput: ^5.0.0
  flutter_camera: ^1.0.0
  path_provider: ^2.1.4
  synchronized: ^3.3.0+3
  logger: ^2.4.0
  permission_handler: ^11.3.1
  path: ^1.9.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  injectable: ^2.4.2
  flutter_animation_progress_bar: ^2.3.1
  video_player: ^2.2.19
  flutter_localizations:
    sdk: flutter
  intl: any
  loading_animation_widget: ^1.2.1
  smart_auth: ^2.0.0
  flutter_svg: ^2.0.10+1
  uuid: ^4.4.2
  flutter_nfc_kit: ^3.4.2
  ndef: ^0.3.3
  passkeys_android: ^2.1.0
  passkeys_ios: ^2.1.0
  passkeys_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  injectable_generator:
  json_serializable: ^6.8.0

flutter:
  fonts:
    - family: IRANSansXFaNum
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Black.ttf
        - asset: assets/fonts/IRANSansXFaNum-Bold.ttf
        - asset: assets/fonts/IRANSansXFaNum-DemiBold.ttf
        - asset: assets/fonts/IRANSansXFaNum-ExtraBlack.ttf
        - asset: assets/fonts/IRANSansXFaNum-ExtraBold.ttf
        - asset: assets/fonts/IRANSansXFaNum-Heavy.ttf
        - asset: assets/fonts/IRANSansXFaNum-Light.ttf
        - asset: assets/fonts/IRANSansXFaNum-Medium.ttf
        - asset: assets/fonts/IRANSansXFaNum-Regular.ttf
        - asset: assets/fonts/IRANSansXFaNum-Thin.ttf
        - asset: assets/fonts/IRANSansXFaNum-UltraLight.ttf


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
