name: banx
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2

  designsystem:
    path: core/designsystem
  data:
    path: core/data
  domain:
    path: core/domain
  utils:
    path: core/utils
  login:
    path: feature/login
  phone:
    path: feature/phone
  verify_otp:
    path: feature/verify_otp
  splash:
    path: feature/splash
  forgot_password:
    path: feature/forgot_password
  signup:
    path: feature/signup
  reset_password:
    path: feature/reset_password
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  melos: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path_android: "assets/images/x1.png"
  image_path_ios: "assets/images/x1.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
    image_path: "assets/images/x1.png"

flutter:
  fonts:
    - family: IranSansX
      fonts:
        - asset: assets/fonts/iransansx-bold.ttf
        - asset: assets/fonts/iransansx-regular.ttf


  uses-material-design: true

  assets:
    - assets/images/x1.png
    - assets/images/banx-logo.png
    - assets/images/banx-logo.svg
    - assets/images/slide-01.png
    - assets/images/slide-02.png
    - assets/images/slide-03.png
    - assets/images/circle_user.svg