name: initial
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../../core/domain
  data:
    path: ../../core/data
  designsystem:
    path: ../../core/designsystem
  utils:
    path: ../../core/utils
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.banx.initial
    iosBundleIdentifier: com.banx.initial
